### ISSUE TITLE
Subject missing from Metadata StreamInfo deserialization?

### ISSUE THREAD

**Issue by ejuntu** [mamaar/Liftbridge.Net#9]
Hi! I've been doing a Liftbridge .NET implementation for a pilot project and came across stream subject info missing from Streaminfo deserializing. Is there a reason it's missing or should I generate pull request for the fix? It's a one-liner "Subject=proto.Subject," anyway.

**Comment by mamaar** [comment]
Hi! 
Thanks for noticing. The library is still in early development and I am not using it myself yet.
This should be fixed, preferably with a test case.

A pull request is very welcome, or just give me a day or two :)

**Comment by mamaar** [comment]
Thanks for the PR. You should know that the library is developed initially for learning C# and .NET. Please feel free to give feedback on any bad practices or other improvements to make Liftbridge.Net better and follow common conventions.
